version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: backend_php
    ports:
      - 8080:80
    volumes:
      - ./www/:/var/www/html
    depends_on:
      - database
    networks:
      php_network:
        aliases:
          - host_php

  database:
    build:
      context: .
      dockerfile: mariadb.dockerfile
    container_name: mariadb_dfz
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "custom_db"
      MYSQL_ROOT_PASSWORD: "custom.2023"
    volumes:
      - ./schemas/:/var/lib/mysql
    networks:
      php_network:
        aliases:
          - host_mariadb

volumes:
  www: {}
  schemas: {}

networks:
  php_network:
    name: php_net
    driver: bridge
    ipam:
      driver: default
